# Generated by Django 5.2.9 on 2025-12-26 13:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gateways', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_ping', models.DateTimeField(default=django.utils.timezone.now)),
                ('messages_sent', models.IntegerField(default=0)),
                ('messages_received', models.IntegerField(default=0)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bridge_sessions', to='gateways.gateway')),
            ],
            options={
                'db_table': 'bridge_sessions',
                'ordering': ['-connected_at'],
            },
        ),
    ]
