# Generated by Django 5.2.9 on 2025-12-26 13:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('home_id', models.UUIDField(db_index=True, unique=True)),
                ('secret_hash', models.CharField(max_length=256)),
                ('public_key', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('online', 'Online'), ('offline', 'Offline'), ('revoked', 'Revoked')], default='provisioning', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gateways',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('home_id', models.UUIDField(db_index=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('user', 'User'), ('viewer', 'Viewer')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'home_permissions',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'home_id')},
            },
        ),
    ]
