# Generated by Django 5.2.9 on 2025-12-26 13:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gateways', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeMetadata',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lon', models.FloatField(blank=True, null=True)),
                ('device_count', models.IntegerField(default=0)),
                ('scene_count', models.IntegerField(default=0)),
                ('automation_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('gateway', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_metadata', to='gateways.gateway')),
            ],
            options={
                'verbose_name': 'Home Metadata',
                'verbose_name_plural': 'Home Metadata',
                'db_table': 'home_metadata',
            },
        ),
    ]
