# Generated by Django 5.2.9 on 2025-12-27 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_id', models.IntegerField(help_text='ID on the local gateway')),
                ('name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=50)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('is_online', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='homes.homemetadata')),
            ],
            options={
                'unique_together': {('home', 'edge_id')},
            },
        ),
    ]
