# Generated by Django 5.2.9 on 2026-01-10 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_synceddevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_id', models.IntegerField(help_text='Automation ID on local server')),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('trigger_logic', models.CharField(default='AND', max_length=3)),
                ('cooldown_seconds', models.IntegerField(default=60)),
                ('triggers', models.JSONField(default=list)),
                ('actions', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='homes.homemetadata')),
            ],
            options={
                'verbose_name': 'Cached Automation',
                'verbose_name_plural': 'Cached Automations',
                'unique_together': {('home', 'edge_id')},
            },
        ),
        migrations.CreateModel(
            name='CachedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_id', models.IntegerField(help_text='Entity ID on local server')),
                ('name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=50)),
                ('subtype', models.CharField(blank=True, max_length=50)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('is_controllable', models.BooleanField(default=False)),
                ('device_id', models.IntegerField(blank=True, null=True)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('device_node_name', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('state_topic', models.CharField(blank=True, max_length=500)),
                ('command_topic', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='homes.homemetadata')),
            ],
            options={
                'verbose_name': 'Cached Entity',
                'verbose_name_plural': 'Cached Entities',
                'unique_together': {('home', 'edge_id')},
            },
        ),
        migrations.CreateModel(
            name='CachedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_id', models.IntegerField(help_text='Location ID on local server')),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='homes.homemetadata')),
            ],
            options={
                'verbose_name': 'Cached Location',
                'verbose_name_plural': 'Cached Locations',
                'unique_together': {('home', 'edge_id')},
            },
        ),
        migrations.CreateModel(
            name='CachedScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_id', models.IntegerField(help_text='Scene ID on local server')),
                ('name', models.CharField(max_length=255)),
                ('actions', models.JSONField(default=list, help_text='List of scene actions')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='homes.homemetadata')),
            ],
            options={
                'verbose_name': 'Cached Scene',
                'verbose_name_plural': 'Cached Scenes',
                'unique_together': {('home', 'edge_id')},
            },
        ),
    ]
